development:
  adapter: postgresql
  encoding: unicode
  database: et_reporting_dev
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: et_reporting_tets
  pool: 5
  host: localhost
  password:

